services:
  - type: web
    name: jump-slasher
    env: node
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: jump-slasher
          envVarKey: PORT
